# Tensorflow Basics

Notebook for taking notes and trialing out code for the Tensorflow 2.0 Basics tutorial (https://www.tensorflow.org/tutorials/quickstart/beginner).

In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
# Don't bake in softmax to last layer activation as this may not be numerically stable
predictions = model(x_train[:1]).numpy()
tf.nn.softmax(predictions).numpy()

array([[0.08927496, 0.10330383, 0.10928493, 0.11002354, 0.13594468,
        0.0897333 , 0.03195685, 0.07866019, 0.09588695, 0.15593077]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
# Untrained model on one sample is close to random guess loss
print("Random guess loss: ", -tf.math.log(1/10).numpy()) # 10 categories
print("Our randomly initialised NN: ", loss_fn(y_train[:1], predictions).numpy())

Random guess loss:  2.3025851
Our randomly initialised NN:  2.4109135


In [12]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2975 - accuracy: 0.9139
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1456 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1087 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0886 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0747 - accuracy: 0.9765


In [14]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0777 - accuracy: 0.9757 - 823ms/epoch - 3ms/step


[0.07769825309515, 0.9757000207901001]

In [15]:
probability_model = tf.keras.Sequential([
    model, tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.19425884e-07, 7.04326055e-08, 1.13522314e-04, 9.33228235e-04,
        9.16304740e-11, 2.87639725e-08, 2.44073069e-14, 9.98941243e-01,
        1.06827565e-06, 1.01085170e-05],
       [2.45091480e-09, 1.73488627e-06, 9.99992967e-01, 4.47756020e-06,
        1.03192108e-15, 2.94239129e-07, 3.15649756e-10, 1.80449839e-12,
        4.35412460e-07, 1.11514302e-15],
       [7.95194183e-07, 9.97843385e-01, 2.20519389e-04, 4.52321729e-05,
        1.47831515e-05, 8.49116077e-06, 1.66183236e-05, 1.22564880e-03,
        6.23463013e-04, 1.01089847e-06],
       [9.99990463e-01, 8.69471595e-12, 6.67027462e-06, 9.99018024e-09,
        7.98088280e-08, 2.62063935e-07, 5.49779941e-07, 7.72450335e-07,
        2.61769673e-09, 1.09905511e-06],
       [2.48030437e-06, 4.00901179e-08, 1.73918652e-05, 1.42998226e-06,
        9.97058392e-01, 1.69980819e-06, 1.91434151e-06, 1.16038638e-04,
        5.97266137e-07, 2.80009792e-03]], dtype=float32)>

In [ ]:
# TODO: Play around with layer sizes to see effect on outputs
#       Try loading a different dataset and building a model for that
#       Play around with some of the Keras additional functionality
#       Is there a nice way to store and compare results?